# Makefile

mac_table: mac_table.c ../calcaddr.c
	gcc -o mac_table mac_table.c ../calcaddr.c


debug: mac_table.c ../calcaddr.c
	gcc -g -o mac_table mac_table.c ../calcaddr.c

clean:
	rm -f mac_table

